version: "3"

services:
  harvester:
      image: vicding81/oai-harvester-manager:0.5
      tty: true
      command: /tmp/harvester_src/src/main/scripts/do-harvester.sh
      volumes:
        - ${DATA_FOLDER}:/var/harvester
        - ${HARVESTER_CONFIG}:/tmp/harvester_src/src/main/scripts/config.xml
